// AUTOGENERATED, DO NOT EDIT

using UnityEngine;
using Winch.Core;

namespace DeepSubmergence {
    public static class BakedAssets {
        public static Mesh GetBoxMesh(){
            Mesh boxMesh = new Mesh();
            
            boxMesh.vertices = new Vector3[]{
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f)
            };
            
            boxMesh.normals = new Vector3[]{
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f),
                new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f), new Vector3(1.0f, 2.0f, 3.0f)
            };
            
            boxMesh.uv = new Vector2[]{
                new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f),
                new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f),
                new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f),
                new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f), new Vector2(2.0f, 3.0f)
            };
            
            boxMesh.triangles = new int[]{
                3, 4,
                4, 5
            };
            
            return boxMesh;
        }
    }
}